'use client'
import BottomNav from "./components/BottomNav"
import Header from "./components/Header"
import "./globals.css"
import { Inter } from "next/font/google"
import { dummyData } from "./data"
import { AnimatePresence } from "framer-motion"

const inter = Inter({ subsets: ["latin"] })

// export const metadata = {
//   title: "Youtube created with Next.js | cs.dev",
//   description: "Generated by create next app",
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header videos={dummyData} />
        <AnimatePresence mode="wait">
          <main>{children}</main>
        </AnimatePresence>
        <BottomNav />
      </body>
    </html>
  )
}
